#!/bin/bash

set -euo pipefail

# check if bun is installed
if ! command -v $HOME/.bun/bin/bun &> /dev/null
then
    # ask to install bun
    read -p "Bun is not installed. Do you want to install it now? (y/n) " yn
    case $yn in
        [Yy]* )
            # install bun
            curl -fsSL https://bun.sh/install | bash
            export PATH="$HOME/.bun/bin:$PATH"
            ;;
        * )
            echo "Bun is required to run this script. Exiting."
            exit 1
            ;;
    esac
fi

# check if node_modules exist
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    $HOME/.bun/bin/bun install --production
fi

$HOME/.bun/bin/bun ./scripts/index.ts "$@"