#!/bin/sh

set -e

#!/bin/bash
mkdir -p config/includes.chroot/usr/share/keyrings
curl -fsSL https://repo.leios.dev/public-key.gpg | gpg --dearmor -o config/includes.chroot/usr/share/keyrings/leios-archive-keyring.gpg


lb config noauto \
	--clean \
	--distribution trixie \
	--architectures amd64 \
	--backports true \
	--security true \
	--updates true \
	--source false \
	--mirror-binary "https://deb.debian.org/debian" \
	--mirror-bootstrap "https://deb.debian.org/debian" \
	--archive-areas "main contrib non-free non-free-firmware" \
	--binary-filesystem ext4 \
	--binary-images iso-hybrid \
	--checksums sha256 \
	--debconf-frontend noninteractive \
	--debian-installer live \
	--debian-installer-distribution trixie \
	--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
	--firmware-binary true \
	--firmware-chroot true \
	--initramfs live-boot \
	--linux-packages "linux-image linux-headers" \
	--memtest memtest86+ \
	--iso-publisher LeiCraft_MC \
	--iso-application "LeiOS" \
	--iso-volume LeiOS 0.5.0 AMD64 \
	--image-name leios-0.5.0-amd64.hybrid.iso \
	--bootloaders "grub-pc grub-efi" \
	--bootappend-live "boot=live components quiet username=user hostname=leios" \

"${@}"
