
stages:
  - build_and_publish

variables:
  LIVE_INSTALLER_VERSION:
    value: "0.0.0"
    description: "Version of the LeiOS Live Installer"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "web" && $CI_PIPELINE_SOURCE != "api"
      when : never
    - if: $GIT_DEPLOY_KEY_ID == null
      when: never
    - if: $GIT_DEPLOY_KEY_SECRET == null
      when: never
    - if: $LIVE_INSTALLER_VERSION == "0.0.0"
      when: never
    
    - when: always

build-and-publish-live-iso:
  stage: build_and_publish
  allow_failure: false
  tags:
    - leios-image-builder-amd64

  before_script:
    #- sudo apt-get update
    #- sudo apt-get install -y live-build debootstrap squashfs-tools xorriso syslinux-common
    - |
      if ! command -v bun &> /dev/null
      then
        # install bun
        curl -fsSL https://bun.sh/install | bash
        export PATH="$HOME/.bun/bin:$PATH"
      fi
    - bun install
    # - export CURRENT_DATE_TAG=$(date +%Y%m%d%H%M)
    - export CURRENT_DATE_TAG=$(date +%Y%m%d)
  script:

    - echo "--- Starting build for amd64 ---"

    - ./lli build-and-publish --architecture=amd64 --version=${LIVE_INSTALLER_VERSION}-${CURRENT_DATE_TAG}

    - echo "--- Build for amd64 complete ---"

    - echo "--- Starting build for arm64 ---"

    - ./lli build-and-publish --architecture=arm64 --version=${LIVE_INSTALLER_VERSION}-${CURRENT_DATE_TAG}

    - echo "--- Build for arm64 complete ---"

  after_script:
    - echo "Starting cleanup after build and publish job."
      
    # Clean up any remaining files if necessary
    - rm -rf ./*

    - echo "Build and publish job finished."

