
stages:
  - prepare
  - build_and_publish

variables:
  LIVE_INSTALLER_VERSION:
    value: "0.0.0"
    description: "Version of the LeiOS Live Installer"

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE != "web" && $CI_PIPELINE_SOURCE != "api"
      when : never
    - if: $GIT_DEPLOY_KEY_ID == null
      when: never
    - if: $GIT_DEPLOY_KEY_SECRET == null
      when: never
    - if: $LIVE_INSTALLER_VERSION == "0.0.0"
      when: never
    
    - when: always

prepare-vars:
  stage: prepare
  script:
    # - export CURRENT_DATE_TAG=$(date +%Y%m%d)
    - echo "CURRENT_DATE_TAG=$(date +%Y%m%d)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

build-and-publish-live-iso-amd64:
  stage: build_and_publish
  allow_failure: false
  tags:
    - glar-linux-large-amd64

  before_script:
    - apt-get update
    - apt-get install -y sudo e2fsprogs curl unzip live-build debootstrap squashfs-tools xorriso
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
    - bun install

    - mkdir -p /opt/leios-live-build
    - truncate -s 20G /opt/leios-live-build.img
    - mkfs.ext4 /opt/leios-live-build.img
    - mount -o loop,exec,dev /opt/leios-live-build.img /opt/leios-live-build

  script:
    - echo "--- Starting build for amd64 ---"

    - ./leios-live-build --cwd=/opt/leios-live-build build-and-publish --architecture=amd64 --version=${LIVE_INSTALLER_VERSION}-${CURRENT_DATE_TAG}

    - echo "--- Build for amd64 complete ---"

  after_script:
    - echo "Starting cleanup after build and publish job."
    
    # Clean up any remaining files if necessary
    - rm -rf /opt/leios-live-build
    - umount /opt/leios-live-build
    - rm -f /opt/leios-live-build.img

    - echo "Build and publish job finished."

build-and-publish-live-iso-arm64:
  stage: build_and_publish
  allow_failure: false
  tags:
    - glar-linux-large-amd64

  before_script:
    - apt-get update
    - apt-get install -y sudo e2fsprogs curl unzip live-build debootstrap squashfs-tools xorriso qemu-user-static
  
    - mountpoint -q /proc/sys/fs/binfmt_misc || mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc
    - /usr/lib/systemd/systemd-binfmt

    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
    - bun install

    - mkdir -p /opt/leios-live-build
    - truncate -s 20G /opt/leios-live-build.img
    - mkfs.ext4 /opt/leios-live-build.img
    - mount -o loop,exec,dev /opt/leios-live-build.img /opt/leios-live-build

  script:
    - echo "--- Starting build for arm64 ---"

    - ./leios-live-build --cwd=/opt/leios-live-build build-and-publish --architecture=arm64 --version=${LIVE_INSTALLER_VERSION}-${CURRENT_DATE_TAG}

    - echo "--- Build for arm64 complete ---"

  after_script:
    - echo "Starting cleanup after build and publish job."
      
    # Clean up any remaining files if necessary
    - rm -rf /opt/leios-live-build
    - umount /opt/leios-live-build
    - rm -f /opt/leios-live-build.img

    - echo "Build and publish job finished."


